DIR_LAB               = lab
NAME                  = course-secure-rest-api-oauth2
IMAGE_SOURCE          = https://github.com/spring-academy/course-secure-rest-api-oauth2
CONTAINER_REGISTRY    = 
CONTAINER_REPOSITORY  = course-secure-rest-api-oauth2
version               = latest

env                   = local